version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        working_directory: ~/repo

        environment:
            MAVEN_OPTS: -Xmx3200m

        steps:
            - checkout
            - run: 
                name: Compile
                command: mvn clean compile
            - run:
                name: Test
                command: mvn test
            - run:
                name: Package
                command: package -DskipTests=true
